// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Draw = require("./Canvas/Draw.bs.js");
var Js_math = require("bs-platform/lib/js/js_math.js");
var Behavior = require("./FRAHelpers/Behavior.bs.js");
var Transform = require("./Canvas/Transform.bs.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

var doomfacesImg = (require('./../assets/Doomfaces.png'));

var doomFaces = new Image();

doomFaces.src = doomfacesImg;

var straight = /* record */[
  /* sx */212,
  /* sy */1,
  /* sw */49,
  /* sh */62,
  /* dw */49,
  /* dh */62
];

var right = /* record */[
  /* sx */160,
  /* sy */1,
  /* sw */49,
  /* sh */62,
  /* dw */49,
  /* dh */62
];

var left = /* record */[
  /* sx */264,
  /* sy */1,
  /* sw */49,
  /* sh */62,
  /* dw */49,
  /* dh */62
];

var t0 = window.Date.now();

function wiggle(t) {
  return 60 * Math.sin(2 * Math.PI * 2 * t / 6000);
}

function waggle(t) {
  return 60 * Math.cos(2 * Math.PI * 2 * t / 6000);
}

function goThroughSprites(arr, t, n) {
  var index = Caml_int32.mod_(t, n);
  return Caml_array.caml_array_get(arr, index);
}

var setToCenter = Transform.moveXY(100, 100);

function look(speed, n, t) {
  return goThroughSprites(/* array */[
              left,
              straight,
              right,
              straight
            ], Caml_int32.mod_(Js_math.floor_int(t / 6000 * speed), n), n);
}

var lookB = Behavior.varied((function (t) {
        return Transform.drawSprite(doomFaces, look(10, 4, t));
      }));

var setToCenterB = Behavior.moveXYB(Behavior.$$const(100), Behavior.$$const(100));

function staticFace(param) {
  return Transform.drawSprite(doomFaces, param);
}

function makeSmaller(f, o) {
  return /* record */[
          /* sx */o[/* sx */0],
          /* sy */o[/* sy */1],
          /* sw */o[/* sw */2],
          /* sh */o[/* sh */3],
          /* dw */o[/* dw */4] / f,
          /* dh */o[/* dh */5] / f
        ];
}

function startAt(x, y) {
  return Behavior.moveXYB(Behavior.$$const(x), Behavior.$$const(y));
}

function multB(param, param$1) {
  return Behavior.lift2((function (prim, prim$1) {
                return prim * prim$1;
              }), param, param$1);
}

function speedUp(n) {
  var partial_arg = multB(Behavior.varied(n), Behavior.getTime);
  return (function (param) {
      return Behavior.timeTrans(partial_arg, param);
    });
}

var stretchFun = Behavior.varied((function (t) {
        return 0.5 + 0.5 * Math.sin(Math.PI * t / 6000);
      }));

var newTransform = Behavior.andThenB(Behavior.moveXYB(Behavior.varied(wiggle), Behavior.$$const(20)), Behavior.$$const(staticFace(straight)));

var allTransforms = Behavior.andThenB(Behavior.groupAnim(speedUp((function () {
                  return 2;
                }))(Behavior.andThenB(Behavior.andThenB(startAt(120, 20), Behavior.moveXYB(Behavior.varied(waggle), Behavior.$$const(20))), Behavior.$$const(staticFace(straight))))), Behavior.groupAnim(Behavior.andThenB(Behavior.andThenB(Behavior.andThenB(Behavior.andThenB(startAt(20, 20), Behavior.stretchB(stretchFun)), Behavior.moveXYB(Behavior.varied(wiggle), Behavior.$$const(0))), Behavior.groupAnim(Behavior.andThenB(Behavior.andThenB(Behavior.moveXYB(Behavior.varied(wiggle), Behavior.$$const(0)), setToCenterB), lookB))), Behavior.groupAnim(Behavior.andThenB(Behavior.andThenB(Behavior.moveXYB(Behavior.$$const(0), Behavior.varied(waggle)), setToCenterB), lookB)))));

Draw.animate(allTransforms);

var $less$neg$great = Behavior.andThenB;

exports.doomfacesImg = doomfacesImg;
exports.doomFaces = doomFaces;
exports.straight = straight;
exports.right = right;
exports.left = left;
exports.t0 = t0;
exports.wiggle = wiggle;
exports.waggle = waggle;
exports.goThroughSprites = goThroughSprites;
exports.setToCenter = setToCenter;
exports.look = look;
exports.lookB = lookB;
exports.setToCenterB = setToCenterB;
exports.staticFace = staticFace;
exports.makeSmaller = makeSmaller;
exports.startAt = startAt;
exports.$less$neg$great = $less$neg$great;
exports.multB = multB;
exports.speedUp = speedUp;
exports.stretchFun = stretchFun;
exports.newTransform = newTransform;
exports.allTransforms = allTransforms;
/* doomfacesImg Not a pure module */
