// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Draw = require("./Canvas/Draw.bs.js");
var Js_math = require("bs-platform/lib/js/js_math.js");
var Behavior = require("./FRAHelpers/Behavior.bs.js");
var Transform = require("./Canvas/Transform.bs.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

var doomfacesImg = (require('./../assets/Doomfaces.png'));

var doomFaces = new Image();

doomFaces.src = doomfacesImg;

var straight = /* record */[
  /* sx */212,
  /* sy */1,
  /* sw */49,
  /* sh */62
];

var right = /* record */[
  /* sx */160,
  /* sy */1,
  /* sw */49,
  /* sh */62
];

var left = /* record */[
  /* sx */264,
  /* sy */1,
  /* sw */49,
  /* sh */62
];

var t0 = window.Date.now();

function wiggle(t) {
  return 60 * Math.sin(2 * Math.PI * 2 * t / 6000);
}

function waggle(t) {
  return 60 * Math.cos(2 * Math.PI * 2 * t / 6000);
}

function goThroughSprites(t, n) {
  var index = Caml_int32.mod_(t, n);
  var image = Caml_array.caml_array_get(/* array */[
        left,
        straight,
        right,
        straight
      ], index);
  return Transform.drawSprite(doomFaces, image);
}

var setToCenter = Transform.moveXY(100, 100);

function look(speed, n, t) {
  return goThroughSprites(Caml_int32.mod_(Js_math.floor_int(t / 6000 * speed), n), n);
}

function firstFace(t) {
  return Transform.$less$neg$great(Transform.$less$neg$great(Transform.moveXY(wiggle(t), 0), setToCenter), look(10, 4, t));
}

function secondFace(t) {
  return Transform.$less$neg$great(Transform.$less$neg$great(Transform.moveXY(0, waggle(t)), setToCenter), look(15, 4, t));
}

var lookB = Behavior.varied((function (param) {
        return look(10, 4, param);
      }));

var setToCenterB = Behavior.moveXYB(Behavior.$$const(100), Behavior.$$const(100));

var allTransforms = Behavior.$less$neg$plus$neg$great(Behavior.$less$neg$plus$neg$great(Behavior.$less$neg$plus$neg$great(Behavior.moveXYB(Behavior.$$const(20), Behavior.$$const(20)), Behavior.moveXYB(Behavior.varied(wiggle), Behavior.$$const(0))), Behavior.saveTB(Behavior.$less$neg$plus$neg$great(Behavior.$less$neg$plus$neg$great(Behavior.moveXYB(Behavior.varied(wiggle), Behavior.$$const(0)), setToCenterB), lookB))), Behavior.saveTB(Behavior.$less$neg$plus$neg$great(Behavior.$less$neg$plus$neg$great(Behavior.moveXYB(Behavior.$$const(0), Behavior.varied(waggle)), setToCenterB), lookB)));

function animate() {
  window.requestAnimationFrame((function (param) {
          return Draw.drawEngineB(allTransforms, param);
        }));
  return /* () */0;
}

animate(/* () */0);

exports.doomfacesImg = doomfacesImg;
exports.doomFaces = doomFaces;
exports.straight = straight;
exports.right = right;
exports.left = left;
exports.t0 = t0;
exports.wiggle = wiggle;
exports.waggle = waggle;
exports.goThroughSprites = goThroughSprites;
exports.setToCenter = setToCenter;
exports.look = look;
exports.firstFace = firstFace;
exports.secondFace = secondFace;
exports.lookB = lookB;
exports.setToCenterB = setToCenterB;
exports.allTransforms = allTransforms;
exports.animate = animate;
/* doomfacesImg Not a pure module */
