// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';


var getById = (function(arg) {
  return document.getElementById(arg)
 });

exports.getById = getById;
/* getById Not a pure module */
