// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Canvas = require("./Canvas.bs.js");
var Transform = require("./Transform.bs.js");

function renderSprite(ctx, image, sprite) {
  ctx.drawImage(image, sprite[/* sx */0], sprite[/* sy */1], sprite[/* sw */2], sprite[/* sh */3], 0, 0, sprite[/* sw */2], sprite[/* sh */3]);
  return /* () */0;
}

var elem = Curry._1(Canvas.getById, "canvas");

function drawEngine(allTransforms, t) {
  var ctx = elem.getContext("2d");
  ctx.globalCompositeOperation = "multiply";
  ctx.imageSmoothingEnabled = false;
  ctx.clearRect(0, 0, 300, 300);
  ctx.save();
  Transform.runAllTransforms(ctx, Curry._1(allTransforms, t));
  return window.requestAnimationFrame((function (param) {
                return drawEngine(allTransforms, param);
              }));
}

exports.renderSprite = renderSprite;
exports.elem = elem;
exports.drawEngine = drawEngine;
/* elem Not a pure module */
